version: '3.7'

services:

    reverse-proxy:
        image: traefik:v2.2
        ports:
            - '8080:8080'
            - '8001:8001'
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./traefik:/etc/traefik
        networks:
            # Attach the traefik container to the default network (which is the global "gateway" network)
            - default
networks:
    default:
        external:
            name: gateway